name: Build debug APK
on:
  pull_request:
jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Debug APK
          path: sample/build/outputs/apk/debug/**.apk
      - uses: actions/upload-artifact@v4
        with:
          name: Debug Tangem Demo APK
          path: tangem-demo/build/outputs/apk/debug/**.apk
